function Invoke-OpenCode-Safe {
    param (
        [string]$Prompt,
        [string]$OutputFile
    )
    Write-Host "Asking OpenCode for $OutputFile ..."
    $body = @{
        model = "qwen2.5-coder:7b"
        prompt = $Prompt
        stream = $false
    } | ConvertTo-Json
    
    $response = Invoke-RestMethod -Uri "http://localhost:11434/api/generate" -Method Post -Body $body -ContentType "application/json" -TimeoutSec 3600
    
    $raw = $response.response
    
    # Extract code between triple backticks if present
    if ($raw -match '(?s)```[a-zA-Z]*\n(.*?)```') {
        $clean = $matches[1]
    } else {
        $clean = $raw
    }
    
    # Remove BOM if present
    $clean = $clean -replace '^\xEF\xBB\xBF', ''
    
    $clean | Out-File -FilePath $OutputFile -Encoding utf8
    Write-Host "Generated $OutputFile"
}

# 1. AI Logic (Backend)
$prompt_ai = "You are OpenCode. Write a complete python script `ai_logic.py`. Define a function `analyze_packet(packet_data: dict) -> str`. It must use `requests` to send a prompt to Ollama at `http://host.docker.internal:11434/api/generate` using model `qwen2.5-coder:7b`. The prompt asks to decide whether to 'accept' or 'drop' the packet based on its src_ip, dst_ip, and protocol. Return only 'accept' or 'drop' as a string. Output ONLY raw python code."
Invoke-OpenCode-Safe -Prompt $prompt_ai -OutputFile "backend\ai_logic.py"

# 2. FastAPI App (Backend)
$prompt_app = "You are OpenCode. Rewrite `app.py` using FastAPI. Import `analyze_packet` from `ai_logic`. Create a FastAPI app with CORS middleware allowing all origins (*). Define endpoints: GET /logs (returns list of logs), GET /rules (returns list of rules), POST /ai/analyze (receives packet_data JSON, calls analyze_packet, appends to logs list, returns {'action': result}). Include `app = FastAPI()`. Output ONLY raw python code."
Invoke-OpenCode-Safe -Prompt $prompt_app -OutputFile "backend\app.py"

# 3. Core Firewall Daemon
$prompt_core = "You are OpenCode. Rewrite `firewall_daemon.py` using NetfilterQueue and Scapy (from scapy.all import IP, TCP, UDP). In the packet callback, extract src, dst, proto, sport, dport from the scapy packet. Send this metadata dict via requests.post to `http://127.0.0.1:8080/ai/analyze`. Based on response json 'action', accept or drop the netfilterqueue packet. Handle exceptions gracefully. Output ONLY raw python code."
Invoke-OpenCode-Safe -Prompt $prompt_core -OutputFile "core\firewall_daemon.py"

# 4. Tailwind Config (Frontend)
$prompt_tw = "You are OpenCode. Write a standard `tailwind.config.js` for Vite+React. content array must include './index.html' and './src/**/*.{js,ts,jsx,tsx}'. Output ONLY raw javascript."
Invoke-OpenCode-Safe -Prompt $prompt_tw -OutputFile "frontend\tailwind.config.js"

# 5. Index CSS (Frontend)
$prompt_css = "You are OpenCode. Write a complete `index.css`. Include `@tailwind base;`, `@tailwind components;`, `@tailwind utilities;`. Add a sleek dark background body styling. Output ONLY raw css."
Invoke-OpenCode-Safe -Prompt $prompt_css -OutputFile "frontend\src\index.css"

# 6. React Dashboard (Frontend)
$prompt_jsx = "You are OpenCode. Write a stunning, premium React Dashboard in `App.jsx`. Use TailwindCSS classes. Design aesthetic: Modern, Glassmorphism, Dark Mode, gradients, premium UI. Fetch data from `http://localhost:8080/logs` every 5 seconds. Display a Sidebar, a 'Live Traffic Logs' table showing packet details and AI decisions, and a 'Firewall Rules' card. Make it extremely visually impressive. Do not use generic colors. Return ONLY raw JSX code."
Invoke-OpenCode-Safe -Prompt $prompt_jsx -OutputFile "frontend\src\App.jsx"

Write-Host "All complete system modules generated by OpenCode!"
