version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: smartshell-backend
    ports:
      - "8080:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434

  frontend:
    build:
      context: ./frontend
    container_name: smartshell-frontend
    ports:
      - "3000:3000"
      - "5173:5173"

  core-firewall:
    build:
      context: ./core
    container_name: smartshell-core
    privileged: true
    network_mode: host
    environment:
      - API_URL=http://127.0.0.1:8080
